% csv_to_iddata_throttle.m
%
% Create multi-experiment iddata objects for throttle->accel identification
% from CSV files generated by accel_fitting_data.py (latest version).
%
% Each pulse_index is treated as one experiment and contains:
%   - pre-step: throttle_delta == 0, throttle == ref_throttle (logged)
%   - step:     throttle_delta != 0, throttle == ref_throttle + delta (logged)
%
% We build:
%   u = throttle_delta
%   y = accel_delta = accel_x - mean(accel_x over pre-step window)
%
% Outputs:
%   - One iddata per CSV exported into base workspace as Zt_<csv_basename>
%   - A summary table exported as throttle_iddata_summary

Ts = 0.01;
THROTTLE_CSV_DIR = "delta_trottle"; % adjust if needed
CSV_GLOB = "*.csv";

files = dir(fullfile(THROTTLE_CSV_DIR, CSV_GLOB));
if isempty(files)
    error("No throttle CSVs found in %s matching %s", THROTTLE_CSV_DIR, CSV_GLOB);
end

summaryRows = [];

for k = 1:numel(files)
    csvPath = fullfile(files(k).folder, files(k).name);
    baseName = erase(files(k).name, ".csv");

    Z = local_make_throttle_iddata(csvPath, Ts);

    varName = matlab.lang.makeValidName("Zt_" + baseName);
    assignin("base", varName, Z);

    row = struct();
    row.csv = string(csvPath);
    row.var = string(varName);
    row.n_experiments = numel(Z.OutputData);
    summaryRows = [summaryRows; row]; %#ok<AGROW>

    fprintf("[%d/%d] Exported %s\n", k, numel(files), varName);
end

throttle_iddata_summary = struct2table(summaryRows);
assignin("base", "throttle_iddata_summary", throttle_iddata_summary);
disp("Done. Workspace now contains Zt_* and throttle_iddata_summary.");


function Z = local_make_throttle_iddata(csvPath, Ts)
    T = readtable(csvPath);

    required = ["pulse_index", "throttle_delta", "accel_x"];
    for c = required
        if ~ismember(c, string(T.Properties.VariableNames))
            error("CSV %s missing required column: %s", csvPath, c);
        end
    end

    pulseIds = unique(T.pulse_index);
    Z = [];

    minStepAbsDelta = 1e-4;

    for i = 1:numel(pulseIds)
        seg = T(T.pulse_index == pulseIds(i), :);
        if height(seg) < 3
            continue;
        end

        u = seg.throttle_delta;
        a = seg.accel_x;

        % Step index: first sample where delta becomes non-zero.
        idxStep = find(abs(u) > minStepAbsDelta, 1, "first");
        if isempty(idxStep) || idxStep < 2
            idxBaseline = 1:min(10, numel(a));
        else
            idxBaseline = 1:(idxStep - 1);
        end

        aBase = mean(a(idxBaseline));
        y = a - aBase;

        z = iddata(y, u, Ts, ...
            "InputName", "throttle_delta", ...
            "OutputName", "accel_delta");

        if isempty(Z)
            Z = z;
        else
            Z = merge(Z, z);
        end
    end

    if isempty(Z)
        error("No valid pulse segments found in %s", csvPath);
    end
end

